### PR TITLE
Fix: Add tus data to ecc-utils-design-form on upload

### LINKED ISSUE #387: bug: tus file upload does not set data on form object on ecc-utils-design-form component
## Description

When a user uploads a file with the tus file option the data is not added to the form object to be returned to the user.

### PR DESCRIPTION
**Pull request by SalihuDickson**
## Description

Fixes #387 

## Checklist

- [ ] My code follows the [contributing guidelines][contributing] of this project.
- [ ] I am aware that all my commits will be squashed into a single commit, using the PR title as the commit message.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have updated the user-facing documentation to describe any new or changed behavior.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have not reduced the existing code coverage.

## Comments

[contributing]: CONTRIBUTING.md

## Summary by Sourcery

Fix the TUS file upload handling in the ecc-utils-design-form component to return upload data and update form state accordingly. Enhance the management of required fields and document the changes with a new changeset file.

Bug Fixes:
- Fix the return value of the handleTusFileUpload function to return upload data instead of void.

Enhancements:
- Update the form handling logic to store and alert field changes when TUS upload data is available.
- Improve the management of required fields by updating the requiredButEmpty list based on form data presence.

Chores:
- Add a changeset file to document the patch changes for the TUS upload data return feature.

### CODE REVIEW

**Comment by SalihuDickson** [comment]
hey @anuragxxd, can you please take a look at this

File: packages/ecc-utils-design/src/components/form/form.ts [hunk 1]
```diff
@@ -548,9 +564,24 @@ export default class EccUtilsDesignForm extends LitElement {
...
+        if (!this.hasUpdated && field.fieldOptions.default) {
+        } else this.requiredButEmpty.push(field.key);
+      } else if (_.get(this.form, newPath)) {
+        // remove from requiredButEmpty
+        this.requiredButEmpty = this.requiredButEmpty.filter(
+          (key) => key !== field.key
+        );
+      }
     }
+
```
Comment (anuragxxd) [inline packages/ecc-utils-design/src/components/form/form.ts:584]: Is this supposed to be in this patch?

**Review by anuragxxd — CHANGES_REQUESTED** [review]
Looks good to me! Just a small comment!

File: packages/ecc-utils-design/src/components/form/form.ts (hunk 1 above)
Comment (SalihuDickson) [reply packages/ecc-utils-design/src/components/form/form.ts]: yes, I made a had to fix a bug and figured i'd just add it to this patch. Or do you think it would be better to create another patch?

**Review by anuragxxd — APPROVED** [review]
